[package]
name = "winkel"
version = "0.1.0"
authors = ["Ian Rehwinkel <ian.rehwinkel@tutanota.com>"]
edition = "2018"

[[test]]
name = "gltests"
path = "gltests/main.rs"
harness = false

[dependencies]
gl = "0.14.0"
freetype-rs = "0.25.0"

[dev-dependencies]
glfw = "0.37.0"
